import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { copyFile, mkdir } from "node:fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Project: Link Tree
*/`;

const production = process.argv[2] === "production";
const distributionDirectory = "dist/link-tree";

// Obsidian installs a plugin from one directory containing the bundle,
// manifest, and stylesheet. Refresh that complete directory after each
// successful build so it can be copied into a vault as-is.
const copyPluginFiles = {
  name: "copy-plugin-files",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0) {
        return;
      }

      await mkdir(distributionDirectory, { recursive: true });
      await Promise.all(
        ["manifest.json", "styles.css"].map((file) =>
          copyFile(file, `${distributionDirectory}/${file}`),
        ),
      );
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  outfile: `${distributionDirectory}/main.js`,
  minify: production,
  plugins: [copyPluginFiles],
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
